services:
  centrifugo:
    image: centrifugo/centrifugo:v5.4.9
    container_name: centrifugo
    mem_limit: "3g"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    command: centrifugo -c config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.json:/centrifugo/config.json
    # remove if not needed
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.centrifugo.entrypoints=http"
      - "traefik.http.routers.centrifugo.rule=Host(`${CENTRIFUGO_API_URL}`)"
      - "traefik.http.routers.centrifugo-secure.entrypoints=https"
      - "traefik.http.routers.centrifugo-secure.rule=Host(`${CENTRIFUGO_API_URL}`)"
      - "traefik.http.routers.centrifugo-secure.tls=true"
      - "traefik.http.routers.centrifugo-secure.tls.certresolver=http"
      - "traefik.http.routers.centrifugo-secure.service=centrifugo"
      - "traefik.http.services.centrifugo.loadbalancer.server.port=${CENTRIFUGO_API_PORT}"
      - "traefik.docker.network=proxy"

# remove if not needed
networks:
  proxy:
    external: true
