services:
  centrifugo:
    image: centrifugo/centrifugo:v5.4.9
    container_name: ${CENTRIFUGO_API_NAME}
    mem_limit: "3g"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
    command: centrifugo -c config.json
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    networks:
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config.json:/centrifugo/config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${CENTRIFUGO_API_NAME}.entrypoints=http"
      - "traefik.http.routers.${CENTRIFUGO_API_NAME}.rule=Host(`${CENTRIFUGO_API_URL}`)"
      - "traefik.http.routers.${CENTRIFUGO_API_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${CENTRIFUGO_API_NAME}-secure.rule=Host(`${CENTRIFUGO_API_URL}`)"
      - "traefik.http.routers.${CENTRIFUGO_API_NAME}-secure.tls=true"
      - "traefik.http.routers.${CENTRIFUGO_API_NAME}-secure.tls.certresolver=http"
      - "traefik.http.routers.${CENTRIFUGO_API_NAME}-secure.service=${CENTRIFUGO_API_NAME}"
      - "traefik.http.services.${CENTRIFUGO_API_NAME}.loadbalancer.server.port=${CENTRIFUGO_API_PORT}"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
